# API Backend (api.avo.local)
server {
    listen 80;
    server_name api.avo.local;
    root /var/www/html/public;

    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass avo-api:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}

# Dev Tools Dashboard (inspector.avo.local)
server {
    listen 80;
    server_name inspector.avo.local;
    root /var/www/html/public;

    index index.php;

    location = / {
        return 301 http://inspector.avo.local/telescope;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass avo-api:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}

# Frontend SPA Vue.js / Vite (app.avo.local)
server {
    listen 80;
    server_name app.avo.local;

    location / {
        proxy_pass http://avo-web:5173;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Support WebSocket pour le HMR de Vite
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
    }
}
